
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const PrivacyPolicyPage = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-grow container py-12">
        <div className="max-w-3xl mx-auto prose">
          <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
          <p className="text-muted-foreground mb-6">Last updated: May 19th, 2025</p>
          
          <p>
            At RoomLab, a service provided by Roomlab. Ltd. ("Roomlab", "we", "us", or "our"), 
            we value and respect the privacy of our users ("user", "you", or "your"). 
            This Privacy Policy outlines how we collect, use, and safeguard your personal 
            information when you access and use our services.
          </p>
          
          <h2 className="text-xl font-bold mt-8 mb-4">Information We Collect</h2>
          <p>We collect the following types of information when you use our services:</p>
          
          <div className="pl-4 border-l-2 border-brand-100 my-4">
            <p className="font-medium">a. Account Information:</p>
            <p>
              When you register an account with RoomLab, we collect your name, email address, 
              and any other information you provide during the signup process.
            </p>
          </div>
          
          <div className="pl-4 border-l-2 border-brand-100 my-4">
            <p className="font-medium">b. Usage Data:</p>
            <p>
              We collect information about your activity on RoomLab, including the designs or 
              images you generate, timestamps of usage, and interactions within the platform.
            </p>
          </div>
          
          <div className="pl-4 border-l-2 border-brand-100 my-4">
            <p className="font-medium">c. Analytics Data:</p>
            <p>
              We utilize analytics tools to gather insights into user behavior, such as pages 
              visited, session durations, and general interaction patterns.
            </p>
          </div>
          
          <h2 className="text-xl font-bold mt-8 mb-4">Use of External Services</h2>
          <p>
            To deliver RoomLab's services, we may integrate third-party tools or platforms. 
            While we strive to work with partners that align with our privacy standards, we 
            cannot guarantee the security of any information processed or stored by these 
            external services.
          </p>
          
          <h2 className="text-xl font-bold mt-8 mb-4">How We Use Your Information</h2>
          <p>Your information is used for the following purposes:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>To operate and maintain our services;</li>
            <li>To enhance user experience and develop new features;</li>
            <li>To detect and prevent fraud or misuse;</li>
            <li>To enforce compliance with our Terms of Service;</li>
            <li>To communicate service updates, offers, and relevant announcements.</li>
          </ul>
          
          <h2 className="text-xl font-bold mt-8 mb-4">Image and Content Review</h2>
          <p>
            To ensure compliance with our Terms of Service, RoomLab may review images or 
            content generated by users. This helps us verify that our platform is not being 
            used to create inappropriate or prohibited material.
          </p>
          
          <h2 className="text-xl font-bold mt-8 mb-4">Data Security</h2>
          <p>
            We implement reasonable security measures to protect your information from 
            unauthorized access or misuse. However, we cannot fully guarantee the security 
            of data transmitted or stored, and we are not liable for any resulting breaches.
          </p>
          
          <h2 className="text-xl font-bold mt-8 mb-4">Changes to This Privacy Policy</h2>
          <p>
            We may revise this Privacy Policy from time to time. Any changes will be posted 
            on our website. Continued use of RoomLab after such updates signifies your 
            acceptance of the revised policy.
          </p>
          
          <h2 className="text-xl font-bold mt-8 mb-4">Contact Us</h2>
          <p>
            If you have questions or concerns regarding this Privacy Policy or your use of 
            RoomLab, please contact us at roomlab@gmail.com
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage;
