// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnrtgrjupqociwwxgdxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucnRncmp1cHFvY2l3d3hnZHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTIwODYsImV4cCI6MjA2MzMyODA4Nn0.H1QneRR2kim03vgLfGw9A-9kWNfiDJ5-iQoaz-Nbsz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);